# Generated by Django 5.0.6 on 2024-06-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquillaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand_owner',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='varieties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
