# Generated by Django 5.0.6 on 2024-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquillaje', '0002_product_type_image_url_alter_brand_owner_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_type',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product_type',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='varieties',
            field=models.TextField(blank=True),
        ),
    ]
